version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        RAILS_ENV: development
        DB_HOST: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aladin_notifier_development
    volumes:
      - aladin_pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  aladin_pgdata:

networks:
  backend:
    driver: bridge
